# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b4cab23332428916600e85358333dfc3da54936eeac9dab3638a2c6461ebba228c2e0ec93dd3a7ad828378650cdc4866d6d0755d99250dd906bfb70d5f1875

test:
  secret_key_base: e6aefab2dbc21f2aec08e8e4a327df9bc14cf8d571f74025adb3d6355e24d5495eb7a10ef4f5c9da0723e30aa82bdeb72320619c7769b96bd205fc8a6883cb57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
